apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: investment-system
spec:
  selector:
    app: investment-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
